### ISSUE TITLE
is there any way to know when each version is valid from?

### ISSUE THREAD

**Issue by alexrecarey** [massayoshi/infinity-army-backup#2]
Hi massayoshi! Firstly, thank you for this wonderful resource!

I'm trying to load the file that is valid on a certain date. Have you found the army version strings (like for example `7.2383.46.json`) are related to dates? The first two digits do seem like the year but I'm not sure if the rest of them are actually day / month or not.

Thank you!

**Comment by massayoshi** [comment]
hey @alexrecarey thank you!

to be honest I haven't thought about that and by doing a quick comparison between the version number and the date it was committed (I ran the script daily) the only other thing is that the first digit is the army version.

what exactly are you trying to accomplish?

**Comment by alexrecarey** [comment]
I have Army Lists saved from different dates that need the correct army version to be able to decode. 

For example Steel Phallanx lists from before the rework that include Patroclus, or even CA lists that if I use the current version show up as 320 points, but were actually 300 points at the time they were written. 

If you run the script daily and commit new files as soon as you find them, then I can trust the added date for each file and I think that should be enough! Thank you.
